node{
	stage('SCM Checkout'){
		git 'https://github.com/ravindkm/docker-java.git'
	}
	stage('Mvn Package'){
		def mvnHome = tool name: 'maven-3',type:'maven'
		
		def mvnCMD = "${mvnHome}/bin/mvn"
		def JAVA_HOME = "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.amzn2.0.1.x86_64"
		sh "${mvnCMD} -f WelcomeDocker/pom.xml clean package"
	}
}