node{
	stage('SCM Checkout'){
		git 'https://github.com/ravindkm/docker-java.git'
	}
	stage('Mvn Package'){
		def mvnHome = tool name: 'maven-3',type:'maven'
		def javaHome = tool name: 'java8', type: 'jdk'
		def mvnCMD = "${mvnHome}/bin/mvn"
		def JAVA_HOME = "${javaHome}"
		sh "${mvnCMD} -f WelcomeDocker/pom.xml clean package"
	}
}